(() => {
  const LEAD_KEY="avodahBookingLeadId",IDEMPOTENCY_KEY="avodahBookingIdempotencyKey",STATE_KEY="avodahConfirmationState";
  const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
  const readLead=()=>{try{return sessionStorage.getItem(LEAD_KEY)||""}catch{return""}};
  const setState=(state)=>{try{sessionStorage.setItem(STATE_KEY,JSON.stringify(state))}catch{};window.AvodahConfirmation?.renderState?.(state)};
  const key=()=>{try{let value=sessionStorage.getItem(IDEMPOTENCY_KEY)||"";if(!value){value=crypto.randomUUID();sessionStorage.setItem(IDEMPOTENCY_KEY,value)}return value}catch{return crypto.randomUUID()}};
  const clear=()=>{try{sessionStorage.removeItem(LEAD_KEY);sessionStorage.removeItem(IDEMPOTENCY_KEY)}catch{}};
  const format=(iso)=>new Intl.DateTimeFormat("en-PH",{timeZone:"Asia/Manila",dateStyle:"full",timeStyle:"short"}).format(new Date(iso));
  const recovery=async(leadId,code,start="",retryable=false)=>{const body=new URLSearchParams({"form-name":"consultation-recovery",lead_submission_id:leadId,failure_code:String(code).slice(0,80),recovery_status:"MANUAL_FOLLOW_UP_REQUIRED",requested_start:String(start).slice(0,80),retryable:String(retryable),recorded_at:new Date().toISOString()});try{return(await fetch("/",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:body.toString()})).ok}catch{return false}};
  const setup=(widget,leadId)=>{
    if(!UUID.test(leadId)||widget.dataset.bookingReady)return;widget.dataset.bookingReady="true";widget.hidden=false;
    const open=widget.querySelector("[data-booking-open]"),panel=widget.querySelector("[data-booking-panel]"),status=widget.querySelector("[data-booking-status]"),date=widget.querySelector("[data-booking-date]"),times=widget.querySelector("[data-booking-times]"),selection=widget.querySelector("[data-booking-selection]"),confirm=widget.querySelector("[data-booking-confirm]"),fallback=widget.querySelector("[data-booking-fallback]"),manual=widget.querySelector("[data-booking-manual]");let days=[],selected="";
    const manualFollowup=async(code,message,retryable=false)=>{const recorded=await recovery(leadId,code,selected,retryable);setState({workflow:"consultation",state:code==="NO_AVAILABLE_SCHEDULE"?"no_available_schedule":"manual_followup_required",reference:leadId,recovery_recorded:recorded});status.textContent=message;fallback.hidden=false;window.AvodahAnalytics?.track("consultation_manual_followup",{workflow:"consultation",status:code.toLowerCase(),retryable})};
    const render=()=>{const day=days.find(item=>item.date===date.value);times.replaceChildren();selected="";selection.textContent="";confirm.disabled=true;if(!day?.slots?.length){times.textContent="No available times for this date.";return}day.slots.forEach(slot=>{const button=document.createElement("button");button.type="button";button.className="booking-time-button";button.textContent=slot.label;button.setAttribute("aria-pressed","false");button.addEventListener("click",()=>{times.querySelectorAll("button").forEach(item=>{item.classList.toggle("is-selected",item===button);item.setAttribute("aria-pressed",String(item===button))});selected=slot.start;selection.textContent=`Selected: ${format(slot.start)} (Asia/Manila)`;confirm.disabled=false});times.appendChild(button)})};
    open.addEventListener("click",async()=>{window.AvodahAnalytics?.track("consultation_booking_started",{workflow:"consultation",status:"availability_requested"});open.disabled=true;panel.hidden=false;status.textContent="Checking available times…";fallback.hidden=true;try{const response=await fetch("/api/booking-slots",{headers:{Accept:"application/json"},cache:"no-store"});const result=await response.json();if(!response.ok||!result.ok)throw new Error(result.code||"AVAILABILITY_FAILED");days=result.days||[];date.replaceChildren();days.forEach(day=>{const option=document.createElement("option");option.value=day.date;option.textContent=`${day.label} — ${day.slots.length} available`;date.appendChild(option)});if(!days.length){await manualFollowup("NO_AVAILABLE_SCHEDULE","No online slots are available. Your intake remains saved.");return}status.textContent=`Times are in Asia/Manila. Appointments are ${result.duration_minutes||30} minutes.`;render()}catch(error){await manualFollowup("AVAILABILITY_FAILED","Online scheduling is temporarily unavailable. Your intake remains saved for manual follow-up.",true);window.AvodahAnalytics?.track("consultation_booking_failed",{workflow:"consultation",status:"availability_failed",retryable:true})}finally{open.hidden=true}});
    date.addEventListener("change",render);
    confirm.addEventListener("click",async()=>{if(!selected)return;confirm.disabled=true;confirm.textContent="Booking…";status.textContent="Reserving your time…";try{const response=await fetch("/api/book-consultation",{method:"POST",headers:{"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify({lead_id:leadId,start:selected,idempotency_key:key()})});const result=await response.json();if(!response.ok||!result.ok){if(result.code==="SLOT_UNAVAILABLE"){setState({workflow:"consultation",state:"slot_unavailable",reference:leadId});status.textContent="That slot was just taken. Refresh and choose another.";open.hidden=false;open.disabled=false;open.textContent="Refresh Available Times";panel.hidden=true;window.AvodahAnalytics?.track("consultation_booking_failed",{workflow:"consultation",status:"slot_unavailable",retryable:true});return}const recorded=await recovery(leadId,result.code||"BOOKING_FAILED",selected,Boolean(result.retryable));setState({workflow:"consultation",state:"booking_failure",reference:leadId,recovery_recorded:recorded});throw new Error(result.error||"Booking failed")}const duplicate=Boolean(result.already_booked);const state={workflow:"consultation",state:duplicate?"duplicate_booking":"appointment_created",reference:result.booking_id||leadId,start:result.start,end:result.end,meeting_method:result.meet_link?"Google Meet":"Meeting details pending",meet_link:result.meet_link||"",management_url:result.management_url||"",reconciliation_required:Boolean(result.reconciliation_required)};try{sessionStorage.setItem(STATE_KEY,JSON.stringify(state))}catch{};clear();window.AvodahAnalytics?.track("consultation_booking_completed",{workflow:"consultation",status:duplicate?"duplicate_detected":"appointment_created",meeting_method:result.meet_link?"google_meet":"pending",duplicate_detected:duplicate});location.href="/booking-confirmation.html"}catch{status.textContent="We could not reserve the time. Your intake remains saved; do not submit it again.";fallback.hidden=false;confirm.disabled=false}finally{confirm.textContent="Confirm Appointment"}});
    manual?.addEventListener("click",()=>manualFollowup("VISITOR_SELECTED_MANUAL_FOLLOWUP","Your consultation request remains saved for manual follow-up."));
  };
  const activate=(leadId)=>{if(!UUID.test(leadId))return;try{sessionStorage.setItem(LEAD_KEY,leadId)}catch{};document.querySelectorAll("[data-booking-widget]").forEach(widget=>setup(widget,leadId))};window.AvodahBooking={activate};const lead=readLead();if(lead)activate(lead);
})();
