const form = document.querySelector("#needs-form");
const steps = [...document.querySelectorAll(".step")];
const nextButton = document.querySelector("#next-button");
const backButton = document.querySelector("#back-button");
const submitButton = document.querySelector("#submit-button");
const branchFields = document.querySelector("#branch-fields");
const contactFields = document.querySelector("#contact-fields");
const progressBar = document.querySelector("#progress-bar");
const progressTrack = document.querySelector(".progress-track");
const stepLabel = document.querySelector("#step-label");
const progressPercent = document.querySelector("#progress-percent");
let currentStep = 1;

const paths = {
  protection: {label:"Protection Guidance",copy:"A conversation about life, health, critical illness, hospitalization, income, or family protection is the most relevant starting point.",link:"/life-insurance-guidance.html",questions:[{name:"protection_for",text:"Who or what would you most like to protect?",options:["Myself","My family or dependents","My income","My employees or key people"]},{name:"protection_priority",text:"Which concern is most important?",options:["Life protection","Critical illness or hospitalization","Income continuity","I am not sure yet"]}]},
  planning: {label:"Financial Planning & Portfolio Review",copy:"A needs-based financial planning conversation can help organize priorities, review current commitments, and explore suitable savings or investment paths.",link:"/investment-planning-portfolio-review.html",questions:[{name:"planning_goal",text:"What is your main planning goal?",options:["Build savings","Review investments","Prepare for retirement","Education or major future expense"]},{name:"planning_stage",text:"Where are you today?",options:["Starting from scratch","I have a plan but need guidance","I already invest and want a review","I am not sure"]}]},
  loan: {label:"Loan Advisory & Preparation",copy:"Loan preparation support can help you understand likely requirements, organize documents, and compare relevant provider pathways. Approval remains with the provider.",link:"/before-applying-for-a-loan.html",questions:[{name:"loan_type",text:"What type of loan are you considering?",options:["Personal loan","Business loan","Auto loan","OFW or seafarer loan","Government employee loan","Not sure"]},{name:"loan_timing",text:"When do you expect to apply?",options:["As soon as possible","Within 1–3 months","Later this year","Just exploring"]}]},
  business: {label:"Business & Legacy Planning",copy:"A business and legacy review can help identify continuity, employee, estate, and succession priorities before exploring specific solutions.",link:"/business-protection-planning.html",questions:[{name:"business_need",text:"What would you like to address first?",options:["Business continuity","Key-person or employee protection","Estate tax preparation","Succession or legacy planning"]},{name:"business_stage",text:"What best describes your stage?",options:["New business","Growing business","Established business","Family-owned business"]}]},
  nonlife: {label:"Non-Life & General Protection",copy:"A general protection review can help identify suitable coverage categories for a vehicle, property, business asset, or trip.",link:"/non-life-insurance-assistance.html",questions:[{name:"asset_to_protect",text:"What needs protection?",options:["Vehicle","Home or property","Business assets","Upcoming trip","Other"]},{name:"coverage_status",text:"Do you currently have coverage?",options:["No coverage yet","Coverage is expiring","I want to compare options","I am not sure"]}]},
  travel: {label:"Travel & Ticketing Assistance",copy:"Travel assistance is the most relevant route for flight planning, visa guidance, passport appointment support, tours, and travel protection.",link:"/travel-ticketing-assistance.html",questions:[{name:"travel_need",text:"What support do you need?",options:["Flight ticketing","Visa guidance","Passport appointment guidance","Tour planning","Travel insurance"]},{name:"travel_timing",text:"When is your expected travel?",options:["Within 30 days","1–3 months","3–6 months","No fixed date yet"]}]}
};

function selectedNeed(){return form.querySelector('input[name="primary_need"]:checked')?.value;}
function renderBranch(){const path=paths[selectedNeed()];branchFields.innerHTML=path.questions.map((q,i)=>`<div class="branch-question"><span>${q.text}</span><div class="branch-options">${q.options.map(o=>`<label><input type="radio" name="${q.name}" value="${o}" required> <span>${o}</span></label>`).join("")}</div><p class="field-error" data-for="${q.name}"></p></div>`).join("");}
function renderResult(){const need=selectedNeed(),path=paths[need];document.querySelector("#result-title").textContent=path.label;document.querySelector("#result-copy").textContent=path.copy;document.querySelector("#result-link").href=path.link;document.querySelector("#service-path").value=path.label;document.querySelector("#primary-need-label").value=form.querySelector('input[name="primary_need"]:checked').nextElementSibling.querySelector("strong").textContent;}
function showStep(number){currentStep=number;steps.forEach(s=>s.classList.toggle("is-active",Number(s.dataset.step)===number));const percent=Math.round(number/3*100);stepLabel.textContent=`Step ${number} of 3`;progressPercent.textContent=`${percent}%`;progressBar.style.width=`${percent}%`;progressTrack.setAttribute("aria-valuenow",String(number));backButton.hidden=number===1;nextButton.hidden=number===3;submitButton.hidden=number!==3;document.querySelector(".intake-card").scrollIntoView({behavior:"smooth",block:"start"});}
function validateStep(){if(currentStep===1){const valid=Boolean(selectedNeed());document.querySelector("#primary-error").textContent=valid?"":"Please choose the need that best matches your situation.";return valid;}if(currentStep===2){let valid=true;branchFields.querySelectorAll(".branch-question").forEach(group=>{const input=group.querySelector("input"),checked=group.querySelector("input:checked"),error=group.querySelector(".field-error");error.textContent=checked?"":"Please select one option.";if(!checked){valid=false;input.focus();}});return valid;}return true;}
nextButton.addEventListener("click",()=>{if(!validateStep())return;if(currentStep===1)renderBranch();if(currentStep===2)renderResult();showStep(currentStep+1);});
backButton.addEventListener("click",()=>showStep(currentStep-1));
form.addEventListener("change",event=>{if(event.target.name==="book_consultation"){const wantsContact=event.target.value==="Yes";contactFields.hidden=!wantsContact;contactFields.querySelectorAll("input,select").forEach(field=>{field.required=wantsContact&&["full_name","mobile_number","location","preferred_contact_method","consent"].includes(field.name);});}});
form.addEventListener("submit",async event=>{event.preventDefault();const choice=form.querySelector('input[name="book_consultation"]:checked');const error=document.querySelector("#submit-error");if(!choice){error.textContent="Please tell us whether you would like a consultation.";return;}if(!form.checkValidity()){error.textContent="Please complete the required contact and consent fields.";form.reportValidity();return;}error.textContent="";submitButton.disabled=true;submitButton.textContent="Sending…";try{const data=new FormData(form);const response=await fetch("/",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams(data).toString()});if(!response.ok)throw new Error("Submission failed");form.hidden=true;document.querySelector(".progress-wrap").hidden=true;const confirmation=document.querySelector("#confirmation");confirmation.hidden=false;document.querySelector("#confirmation-title").textContent=choice.value==="Yes"?"Your consultation request has been received.":"Your needs check is complete.";document.querySelector("#confirmation-copy").textContent=choice.value==="Yes"?"Thank you. An Avodah representative can follow up using your selected contact method. Please allow reasonable time for a response.":"Thank you for using the Avodah needs check. You can explore the suggested service path now and contact Avodah whenever you are ready.";confirmation.focus();}catch{error.textContent="We could not submit your answers just now. Please try again in a moment.";}finally{submitButton.disabled=false;submitButton.textContent="Finish";}});
if(new URLSearchParams(location.search).get("submitted")==="true"){history.replaceState({},"",location.pathname);}
