(() => {
  window.dataLayer=window.dataLayer||[];window.gtag=window.gtag||function(){dataLayer.push(arguments)};window.gtag("consent","update",{analytics_storage:"denied",ad_storage:"denied",ad_user_data:"denied",ad_personalization:"denied"});
  const load=(src)=>{if(document.querySelector(`script[src="${src}"]`))return;const s=document.createElement("script");s.src=src;s.defer=true;document.head.appendChild(s)};load("/analytics.js");load("/cookie-preferences.js");
  const header=document.querySelector(".site-header"),toggle=document.querySelector(".menu-toggle"),nav=document.querySelector(".nav"),faq=document.querySelectorAll(".faq-list details"),form=document.querySelector(".contact-form");
  const ATTR="avodahAttribution",BOOK="avodahBookingLeadId",STATE="avodahConfirmationState";
  const FIELDS=["utm_source","utm_medium","utm_campaign","utm_content","utm_term","campaign_id","adset_id","ad_id","fbclid","landing_page","referrer"];
  const readAttr=()=>{try{return JSON.parse(sessionStorage.getItem(ATTR)||"{}")}catch{return{}}};
  const cleanUrl=(value)=>{try{const url=new URL(value,location.origin);return url.origin+url.pathname}catch{return""}};
  const capture=()=>{const data=readAttr(),params=new URLSearchParams(location.search);FIELDS.slice(0,9).forEach(key=>{const value=params.get(key);if(value)data[key]=value.slice(0,500)});if(!data.landing_page)data.landing_page=location.origin+location.pathname;if(!data.referrer&&document.referrer)data.referrer=cleanUrl(document.referrer);try{sessionStorage.setItem(ATTR,JSON.stringify(data))}catch{};return data};
  const attribution=capture();document.querySelectorAll('a[href^="/needs-check"]').forEach(link=>{const url=new URL(link.href,location.origin);FIELDS.forEach(key=>{if(attribution[key]&&!url.searchParams.has(key))url.searchParams.set(key,attribution[key])});link.href=url.pathname+url.search});
  if(form){FIELDS.forEach(key=>{const input=form.querySelector(`[name="${key}"]`);if(input)input.value=attribution[key]||""});const page=form.querySelector('[name="source_page"]');if(page)page.value=location.pathname}
  if(header&&toggle&&nav){const close=()=>{header.classList.remove("is-open");toggle.setAttribute("aria-expanded","false");toggle.setAttribute("aria-label","Open menu")};toggle.addEventListener("click",()=>{const open=header.classList.toggle("is-open");toggle.setAttribute("aria-expanded",String(open));toggle.setAttribute("aria-label",open?"Close menu":"Open menu")});nav.querySelectorAll("a").forEach(link=>link.addEventListener("click",close));document.addEventListener("click",event=>{if(header.classList.contains("is-open")&&!header.contains(event.target))close()});document.addEventListener("keydown",event=>{if(event.key==="Escape")close()});addEventListener("resize",()=>{if(matchMedia("(min-width:901px)").matches)close()})}
  faq.forEach((details,index)=>{const summary=details.querySelector("summary");if(!summary)return;let answer=details.querySelector(".faq-answer");if(!answer){answer=document.createElement("div");answer.className="faq-answer";[...details.childNodes].filter(node=>node!==summary).forEach(node=>answer.appendChild(node));details.appendChild(answer)}answer.id||=`faq-answer-${index+1}`;summary.setAttribute("aria-controls",answer.id);summary.setAttribute("aria-expanded",String(details.open));answer.style.maxHeight=details.open?`${answer.scrollHeight}px`:"0px";summary.addEventListener("click",event=>{event.preventDefault();const opening=!details.open;if(opening)details.open=true;requestAnimationFrame(()=>{summary.setAttribute("aria-expanded",String(opening));details.classList.toggle("is-open",opening);answer.style.maxHeight=opening?`${answer.scrollHeight}px`:"0px"});if(!opening)answer.addEventListener("transitionend",()=>{if(!details.classList.contains("is-open"))details.open=false},{once:true})})});
  const uuid=()=>{if(crypto.randomUUID)return crypto.randomUUID();const bytes=new Uint8Array(16);crypto.getRandomValues(bytes);bytes[6]=(bytes[6]&15)|64;bytes[8]=(bytes[8]&63)|128;const hex=[...bytes].map(v=>v.toString(16).padStart(2,"0")).join("");return`${hex.slice(0,8)}-${hex.slice(8,12)}-${hex.slice(12,16)}-${hex.slice(16,20)}-${hex.slice(20)}`};
  const addConsent=()=>{if(!form||form.querySelector('[name="marketing_consent"]'))return;const required=form.querySelector('[name="consent"]');if(required){required.name="processing_consent";required.dataset.error="Please acknowledge processing of your consultation request."}const anchor=required?.closest("label")||form.querySelector('button[type="submit"]');const hidden=document.createElement("div");hidden.innerHTML='<input type="hidden" name="processing_consent_version" value="consultation-processing-v1-2026-07-24"><input type="hidden" name="marketing_consent_version" value="marketing-v1-2026-07-24"><input type="hidden" name="consent_recorded_at" value="">';form.insertBefore(hidden,anchor);const optional=document.createElement("label");optional.className="consent-check optional-marketing-consent";optional.innerHTML='<input type="checkbox" name="marketing_consent" value="yes"><span><strong>Optional marketing permission:</strong> I would like future educational updates, campaigns, or promotional messages. This is optional, unchecked by default, and does not affect this request.</span><span aria-live="polite" class="field-error"></span>';anchor.insertAdjacentElement("afterend",optional)};addConsent();
  if(!form)return;const status=form.querySelector(".form-status"),honeypot=form.querySelector('[name="bot-field"]'),submit=form.querySelector('button[type="submit"]'),original=submit?.textContent||"Submit Consultation Request";let started=false;
  const controls=()=>[...form.querySelectorAll("input,select,textarea")].filter(field=>field.type!=="hidden"&&field.name!=="bot-field");
  const validate=field=>{const value=field.type==="checkbox"?field.checked:field.value.trim();let message="";if(field.required&&!value)message=field.dataset.error||"This field is required.";else if(field.type==="email"&&value&&!field.validity.valid)message="Please enter a valid email address.";field.classList.toggle("is-invalid",Boolean(message));field.classList.toggle("is-valid",!message&&Boolean(value));field.setAttribute("aria-invalid",String(Boolean(message)));const error=field.closest("label")?.querySelector(".field-error");if(error)error.textContent=message;return!message};
  controls().forEach(field=>{const activity=()=>{if(!started){started=true;window.AvodahAnalytics?.track("consultation_form_started",{workflow:"consultation",status:"started"})}validate(field);if(status){status.textContent="";status.className="form-status"}};field.addEventListener("input",activity);field.addEventListener("change",activity);field.addEventListener("blur",()=>validate(field))});
  form.addEventListener("submit",async event=>{event.preventDefault();const fields=controls(),valid=fields.map(validate).every(Boolean);if(honeypot?.value)return;if(!valid){if(status){status.textContent="Please review the highlighted fields.";status.className="form-status is-visible is-error"}fields.find(field=>field.classList.contains("is-invalid"))?.focus();return}const lead=uuid();const leadInput=form.querySelector('[name="lead_submission_id"]');if(leadInput)leadInput.value=lead;const consentAt=form.querySelector('[name="consent_recorded_at"]');if(consentAt)consentAt.value=new Date().toISOString();if(submit){submit.disabled=true;submit.textContent="Sending..."}try{const response=await fetch("/",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams(new FormData(form)).toString()});if(!response.ok)throw new Error("submission_failed");try{sessionStorage.setItem(BOOK,lead);sessionStorage.setItem(STATE,JSON.stringify({workflow:"consultation",state:"intake_received_no_schedule",reference:lead}))}catch{};window.AvodahAnalytics?.track("consultation_form_completed",{workflow:"consultation",status:"intake_received",campaign_source:attribution.utm_source||"direct",campaign_medium:attribution.utm_medium||"none",campaign_name:attribution.utm_campaign||"none"});location.href="/consultation-confirmation.html"}catch{if(status){status.textContent="We could not send your inquiry. Your entries remain on this page; try again or use the contact fallback.";status.className="form-status is-visible is-error"}}finally{if(submit){submit.disabled=false;submit.textContent=original}}});
})();
